spring.application.name=OrderService
server.port=8081

# ================= KAFKA PRODUCER CONFIG (Existing) =================
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
# Prevents class-casting errors when the other service tries to read the JSON
spring.kafka.producer.properties.spring.json.add.type.headers=false


# ================= KAFKA CONSUMER CONFIG (NEW) =================
spring.kafka.consumer.group-id=order-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Trust all packages so it can deserialize the JSON payload safely
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Tell Spring Kafka exactly which DTO class to map the incoming JSON to
spring.kafka.consumer.properties.spring.json.value.default.type=com.example.demo.dto.InventoryEvent

spring.datasource.url = jdbc:mysql://localhost:3306/order_service_db
spring.datasource.username = root
spring.datasource.password = Mysql@123
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.jpa.database-platform = org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.formate_sql = true
